branches:
  only:
  - source

deploy:
  edge:
    branch: v1.8.47
  local_dir: _site
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: master
  on:
    all_branches: true

script: bash -x build.sh
